name: "GitHub Advanced Security - Metrics Report Action"
on:
  pull_request:
    branches:
      - main

jobs:
  ghas-metrics-report:
    name: GitHub Advanced Security - Metrics Report Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GHAS Metrics Report
        uses: theztefan/ghas-metrics-report@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          repo: ${{ github.event.repository.name }}
          org: pure-spectacle
          features: "dependabot, code-scanning, secret-scanning"
          frequency: "daily"
          output-format: "pdf"
          
      - name: Upload GHAS metrics report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghas-metrics-report
          path: ${{ github.workspace }}/ghas-report.*
